CREATE TABLE PERSON_TMP2 (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null
);

insert into PERSON_TMP2 (first_name, last_name) values ('Toto', 'Syer');
